name: Go

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOCACHE: ${{ github.workspace }}/.gocache

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache Files
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.gocache
        key: ${{ runner.os }}-gocache-file

    - name: Mod tidy
      run: |
        go mod tidy

    - name: Build magneticod
      run: |
        go build

    - name: Build magneticow.exe
      run: |
        GOOS=windows GOARCH=amd64 go build

    - name: List Package dir
      run: |
        ls -la

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: magneticos.${{runner.os}}-${{runner.arch}}
        path: |
          magneticos

    - name: Upload artifact windows
      uses: actions/upload-artifact@v2
      with:
        name: magneticos.win64
        path: |
          magneticos.exe
