name: Go

# on: [push, pull_request, workflow_dispatch]
on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOCACHE: ${{ github.workspace }}/.gocache

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache Files
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.gocache
        key: ${{ runner.os }}-gocache-file

    #- name: Install go-bindata
    #  run: |
    #    go install github.com/kevinburke/go-bindata/go-bindata@v3.24.0

    - name: Mod tidy
      run: |
        go mod tidy

    - name: Build magneticod
      run: |
        go build --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`"

    - name: Build magneticow.exe
      run: |
        #GOOS=windows GOARCH=amd64 go build --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`" ./cmd/magneticow
        # ls -laR

    - name: List Package dir
      run: |
        ls -la
